# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapDataCleaner
                                 A QGIS plugin
 This plugin downloads and cleans data for mapping.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-09
        copyright            : (C) 2020 by McKenzie Intelligence
        email                : dev@mckenzieintelligence.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapDataCleaner class from file MapDataCleaner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_data_cleaner import MapDataCleaner
    return MapDataCleaner(iface)
